### PR TITLE
Introduce bbp-morphology-workflow module

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
I hope I did this correctly

**Comment by adevress** [comment]
You did, but if you want it to be built and deploy, you need to add it to the "set" related to nse or in modules.all :)

**Comment by mgeplf** [comment]
k, added
tnx

**Comment by adevress** [comment]
Note: Please press the magic redeployment button if you want it deployed https://bbpcode.epfl.ch/ci/view/hpc/job/hpc.redeploy-modules.nix/

**Pull request merged**
