### PR TITLE
add plottools

### PR DESCRIPTION
**Pull request by genric**
@wizmer pls.

### CODE REVIEW

**Comment by tristan0x** [comment]
Can you please reference those 2 new Python packages somewhere in `bbp/modules/default.nix` as dedicated modules or part of an existing one so that they are built by continuous integration?

**Comment by tristan0x** [comment]
Aren't these packages useful for an existing module or a new one that _make sense_? Because this will deploy a `phony-python-libs` module on bb5.

**Comment by genric** [comment]
Currently we use them to compose nix-shell with whatever packages you want. So this module is just to trigger the CI.

**Comment by genric** [comment]
@wizmer pls?

**Pull request merged**
