### PR TITLE
Use latest nixpkgs-base

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by tristan0x** [comment]
retest this please

**Comment by tristan0x** [comment]
Jenkins build crashes because not enough memory. I am building everything in an openstack VM to fill BBP Nix cache manually.

**Comment by pramodk** [comment]
Is this related to nix-v2?

**Comment by tristan0x** [comment]
> Is this related to nix-v2?

No. I simply want to get Adrien's changes before submitting new ones.

**Comment by tristan0x** [comment]
retest this please

**Pull request merged**
