### PR TITLE
Update Brayns to latest version

### PR DESCRIPTION
**Pull request by tribal-tec**
nix-build works fine, but it depends on non-nix libraries:
```
libicui18n.so.42 => /usr/lib64/libicui18n.so.42 (0x0000003a45600000)
libicuuc.so.42 => /usr/lib64/libicuuc.so.42 (0x0000003a41e00000)
libicudata.so.42 => /usr/lib64/libicudata.so.42 (0x0000003617e00000)
libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x0000003a37600000)
libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x0000003a36e00000)
```

### CODE REVIEW

**Comment by adevress** [comment]
@tribal-tec  Can you give  me the command you used and on which machien to get this result Daniel ?

**Comment by tribal-tec** [comment]
I did `nix-build . -A modules.brayns` on bbpviz2.cscs.ch

**Comment by adevress** [comment]
I'm passing by

**Comment by tribal-tec** [comment]
Ok, good to go now. Memo to myself: unset LD_LIBRARY_PATH!!

**Comment by tristan0x** [comment]
@tribal-tec Can I merge this one?

**Comment by tribal-tec** [comment]
Yes, sure.

**Pull request merged**
