### PR TITLE
Added generation of env module for RTNeuron 2

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by tristan0x** [comment]
`rtneuron` and `rtneuron2` module pkgs are the same. Shouldn't `rtneuron2` module use `rtneuron2` pkg?

**Comment by hernando** [comment]
I rely on the version to generate a different module path. At least rtneuron creates a nix/viz/rtneuron/3.0.0 module, and I expect rtneuron2 to create nix/viz/rtneuron/2.12.0. But maybe it doesn't work at all like that.

**Comment by hernando** [comment]
I rely on the version to generate a different module path. At least rtneuron creates a nix/viz/rtneuron/3.0.0 module, and I expect rtneuron2 to create nix/viz/rtneuron/2.12.0. But maybe it doesn't work at all like that.

In fact there's something wrong, but I don't know what it is right away.

**Comment by tristan0x** [comment]
rtneuron2 module should use rtneuron2 package:

```diff
diff --git a/bbp/modules/default.nix b/bbp/modules/default.nix
index 104608dc88..06a75ab57b 100644
--- a/bbp/modules/default.nix
+++ b/bbp/modules/default.nix
@@ -1215,7 +1215,7 @@ let
             isLibrary = true;
             description = "rtneuron module generated by nix, old version";
             packages = [
-                            pkgs.rtneuron pkgs.equalizer
+                            pkgs.rtneuron2 pkgs.equalizer
                        ];
             extraContent = "prepend-path LD_LIBRARY_PATH $targetEnv/lib/";
             dependencies = [ brion virtualgl pyqt5 pyopengl ];
```

**Pull request merged**
