### PR TITLE
Bump to Intel composer 2018.0.128

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by pramodskumbhar** [comment]
as discussed, just for the record, `intel 2018` is not considered `stable` (fftw guys saw the issue and last wee we saw issue with NEURON for knl).

**Comment by delalond** [comment]
​Is there a version in between 2017 and 2018 that is considered more stable ? There are additional releases that got released in the last year... Could you maybe advise which one to safely use ?

Tristan, can you create a module for 2018 and call it unstable or something like this ?

________________________________

**Comment by tristan0x** [comment]
@delalond 
There is no major version between 2017 and 2018, but we are currently using initial release of 2017 whereas there have been 5 updates since then.

I have just asked core services to create a module for 2018 (which was already installed but not available as a module) and to install 2017 update 5.

**Comment by pramodskumbhar** [comment]
Update 5 from 2017 should be good enough. Only few weeks ago Theta started using `intel/18.0.0.128` as default with which we saw issues. (then we reverted using `intel/17.0.4.196` available on Theta).

**Pull request merged**
