### PR TITLE
Change package name: neuroM to neurom

### PR DESCRIPTION
**Pull request by wizmer**
... and replaced tabs with spaces

### CODE REVIEW

**Comment by wizmer** [comment]
@tristan0x Is there a convention for the package name. Should it be lower case only ? Also, does defining the variable `pname` in addition to `name` is worth doing ?

Thanks

**Comment by adevress** [comment]
Initially I indeed packaged everything in lowecase, with dash as delimiter. But that's not an absolute rule.

**Comment by wizmer** [comment]
Thanks @adevress. Then maybe it should be enforced when testing the PR ?
While you are here, do have an answer about the `pname` variable ? :)

**Comment by adevress** [comment]
pname has no real usage, it is just useful if you wish to re-use the name without the version inside it in a later field ( for instance to checkout the software from a repository where it is identified by its name in the URL )

**Pull request merged**
