### PR TITLE
add production entities python package

### PR DESCRIPTION
**Pull request by genric**

### CODE REVIEW

**Comment by genric** [comment]
We need attrs version 17.4.0, can this be merged(https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/attrs/default.nix) or I need to create my own attrs 17.4? Thanks.

**Comment by tristan0x** [comment]
Hello @genric 
You can add the attrs 17.4 in `patches/additionalPythonPackages/default.nix`
Furthermore, you might want to register this new package in bbp/modules/default.nix in `nse_base` bucket.

**Comment by genric** [comment]
Thanks @tristan0x, I added 17.4 to the patches.
I think for now it should stay stand-alone, later it will probably make it to the bucket. Thanks.

**Comment by tristan0x** [comment]
Because those 2 packages are not referenced in `bbp/modules/default.nix`, Jenkins bot is not trying to build them.
So I built them on my workstation and it looks fine:

```
$ nix-build -A entity-management -A entity-management_0_1_1\
[...]
/nix/store/m5mdh7dhcijc8mbwslbjcrl2lafkb8p5-python3.6-entity-management-0.1.2
/nix/store/mm3f5v595fn5a4mjdddafpdb0lzgyg1l-python3.6-entity-management-0.1.1
```

**Comment by tristan0x** [comment]
By the way, thanks @genric  for the rebase + squash !

**Comment by genric** [comment]
No problem @tristan0x :)
By the way, do we always need to make a module or it can stay as a nix package and still be build by jenkins bot?

**Comment by genric** [comment]
OK, thanks for the explanation!

**Pull request merged**
