### PR TITLE
Update NEURON with latest github master version (fix coreneuron data generation error)

### PR DESCRIPTION
**Pull request by pramodk**
I am not sure about how we generate `sha256`.

### CODE REVIEW

**Comment by adevress** [comment]
add to whitelist

**Comment by pramodk** [comment]
retest (& merge please)

**Comment by pramodk** [comment]
don't know whats the failure:

```
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (56) Unexpected EOF
/nix/store/vkbh4xbgxvx3v9813d4kdwv8ggwrp038-xz-5.2.2-bin/bin/xz: (stdin): File format not recognized
error: unexpected end-of-file
download of ‘https://cache.nixos.org/nar/10l4lchp1a6xyfbf52862a1vn6dlhnis5y8l3v62r6rnnxqj44yn.nar.xz’ failed: No such file or directory
could not download ‘/nix/store/xi4qqlwcd67l6j55lqi72z1fv9s4hp5d-nss-cacert-3.21’ from any binary cache
fetching path ‘/nix/store/xi4qqlwcd67l6j55lqi72z1fv9s4hp5d-nss-cacert-3.21’ failed with exit code 1
cannot build derivation ‘/nix/store/mq3r1ybrknqyg91b2hq756r3m29l32s3-bbp-459425c.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/x4j7qa22fwlq6jfi5hr0cycxra85hd0l-bbp-864c435.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/sshgj6xsh3pdgh09y4c3x1qnazi5hr2m-bbp-aff82c9.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/sqjabw2jpr0xrh9igqyf9y82f6y1y30y-bbp-d82001e.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/3cnzh1sfgnflhsw70w72l0mk8k49dzzv-neurodamus-1.9.0-201707.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wjvxsgmbbky44g1fqphza0qmrvpjgj1w-neurodamus-1.9.0-201707.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/yhh1rmzv9nh6h2izkik7qjq019xszw9k-neurodamus-1.9.0-201707.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/fqvminsph3j1wan0v0l6pr51bfc8zgfm-neurodamus-coreneuron-1.9.0-201707.drv’: 1 dependencies couldn't be built
killing process 23913
cannot build derivation ‘/nix/store/xfxylbz4q1m5makr0mpm6myy7cncf62a-generated-env-module-coreneuron.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/7a282v6m09mjnqbvrqy7mxii3hck19bw-generated-env-module-neuron-hippocampus.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/i4s9jbravvayaxb5albhb60kri3fqliv-generated-env-module-neuron-savestate.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ci10pz8dy6ki8al6sycklila2hvfib92-generated-env-module-neuron.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/9km3zwk5q4rn2w4ws7rd5wkqqjxhjzpf-coreneuron.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/7xcglz7fmqbglx91c0z5abdlkhrdcmfq-neuron-hippocampus.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/axijmfyw6k6n83b2lpq7k9ss2hza951m-neuron-savestate.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/mgszcyzaxqhhz8bpvdw03ld9a73g421c-neuron.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/m13wf13p41n2syw51j2kqhf8z5k0ifh3-all-modules.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/m13wf13p41n2syw51j2kqhf8z5k0ifh3-all-modules.drv’ failed
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by adevress** [comment]
retest this please

**Pull request merged**
