### PR TITLE
Update 'placement-algorithm' package

### PR DESCRIPTION
**Pull request by arsenius7**

### CODE REVIEW

**Comment by arsenius7** [comment]
Tristan, could you please clarify a some moments wrt versioning and modules.

1) If I don't have any preference for versioning scheme, is there a recommended one? I see different schemes from one repo to another. Should it be 'maj.min.fix'? Or 'YYYY.MM-<git commit>'?
2) What should I do to have the updated version available as a `module`?
3) What should I do if I want `nix/nse/placement-algorithm` module to automatically bring `spark` module? Is it a good idea at all, or should I get `spark-submit` available somehow else?

Thanks.

**Comment by tristan0x** [comment]
Hello @arsenius7 

1. If your code does not have a versioning scheme already, you can just use `YYYY.MM`
1. You have nothing to do in your pull-request. To deploy latest version of modules (*master* branch of bbp-nixpkgs) on viz cluster, execute the following [Jenkins plan](https://bbpcode.epfl.ch/ci/job/hpc.redeploy-modules.nix/)
1. I will have to get back to you on this one...

**Comment by arsenius7** [comment]
OK, thanks, Tristan,

1. I've switched to YYYY.MM-<short revision> scheme, since this package does not have its own versioning scheme yet; nor is it git-tagged.
2. Should I just launch it manually? Is it safe? Do you have an intention of having a regular build there by chance?
3. If that one is a blocker, we can get back to it later, meanwhile I can live with `module load placement-algorithm spark`

**Comment by arsenius7** [comment]
2. Also, it looks like the plan was ran last time in December but there are some modules added this year already (nix/nse/pybinreports/2018.01-3a09ab, for instance). Just out of curiosity, do you use some other way to redeploy in addition to Jenkins plan?

**Comment by tristan0x** [comment]
Hello @arsenius7 

2. Yes everybody can execute the plan. No we do not plan to automate deployment.
3. I think @adevress talked to be about providing spark with Nix but I don't know what the status is.
4. You can use `nix-env` to deploy modules. for instance on your account:
    ```
    $ cd /path/to/bbp-nixpkgs
    $ nix-env -f . -iA modules.placement-algorithm
    $ export MODULEPATH="$NIX_PROFILE/share/modulefiles:$MODULEPATH"
    $ module load nix/placement-algorithm
    ```
    Optionally you can pass `nix-env` another profile to install packages in another location. Typically we provide a path already in `MODULEPATH` to deploy for all users.

**Comment by arsenius7** [comment]
np; hope I did not mess up along the way. :)

**Pull request merged**
