### PR TITLE
Added LD_LIBRARY_PATH export to brayns modules and plugins

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by tristan0x** [comment]
Hello @favreau 
Why do you need to expose `LD_LIBRARY_PATH`. That might mess environment including those modules.
@adevress Any comment about it?

**Comment by favreau** [comment]
Yes, the LD_LIBRARY_PATH has to be exposed. Those modules are actually plugins that are loaded by Brayns. Since all libraries compiled by our modules are Brayns specific, I don't think there is any issue in exposing them. But @adevress 's input is clearly a good idea.

**Comment by tristan0x** [comment]
What about using another environment variable like `BRAYNS_PLUGIN_PATH` for instance ?

**Comment by favreau** [comment]
Hum, the plugins are regular libraries, like any other system dependency. I'd rather leave it to the system to locate the librairies, and not introduce a new env variable that most users will not know about. I copied/pasted this stuff from modules like ospray, qt or gcc, and this appears to be the way @adevress decided to implement it.

**Comment by adevress** [comment]
Hi Cyrille,

That doable to define the PLUGIN_PATH with LD_LIBRARY_PATH. However, I tend to like to keep LD_LIBRARY_PATH as empty as possible to avoid library conflict.

We can accept it for now, but could you implement a specific environment variable for Brayns plugin path in future ? That would be a good thing

**Comment by tribal-tec** [comment]
It's not fully in our hands unfortunately. We use the dynamic library loader from ospray, which just does a simple dlopen. And according to how dlopen works, it checks LD_LIBRARY_PATH, /etc/ld.so.cache. /lib and /usr/lib. So LD_LIBRARY_PATH is our only working solution.

**Comment by adevress** [comment]
@tribal-tec dlopen if you give it an absolute path try to laod precisely this library. Would it be possible for you to ask him to load every plugin you look for under "$BRAYNS_PLUGIN_PATH/plugin_name.so" and fail gracefully if you don't find it, getting back on relative path ?

**Comment by tribal-tec** [comment]
No, they prefix the name we give them...
https://github.com/ospray/ospray/blob/master/components/ospcommon/library.cpp#L147

**Pull request merged**
