### PR TITLE
add latest nse morphsyn

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
After fixing the cmake files so that things aren't loaded during the configure
phase, I'm running into the following problem: 
```
    /nix/store/k57f430jwfkbd8rh88ibarsh2pspl3mg-binutils-2.23.1/bin/ld: cannot find -lvtkCommonDataModel
    /nix/store/k57f430jwfkbd8rh88ibarsh2pspl3mg-binutils-2.23.1/bin/ld: cannot find -lvtkFiltersCore
    /nix/store/k57f430jwfkbd8rh88ibarsh2pspl3mg-binutils-2.23.1/bin/ld: cannot find -lvtkIOLegacy
````
I suspect it's because we're using vtk6, but the nix version is older (5?).

**Comment by mgeplf** [comment]
https://github.com/adevress/nixpkgs-bbp-upstream/blob/43f47848c81edf5edaf819445c6cfe3f77ddafdb/pkgs/development/libraries/vtk/default.nix

seems to be the version we're using.  Upstream has the newest version, from what I can tell.

**Comment by adevress** [comment]
add to whitelist

**Comment by adevress** [comment]
retest this

**Comment by adevress** [comment]
retest this please

**Pull request merged**
