### PR TITLE
Update default.nix

### PR DESCRIPTION
**Pull request by timocafe**
double -> float

### CODE REVIEW

**Comment by adevress** [comment]
add to whitelist

**Comment by adevress** [comment]
retest this please

**Comment by adevress** [comment]
retest this please

**Comment by adevress** [comment]
@timocafe  Your float mode blocks forever the Brunel test

**Comment by timocafe** [comment]
right legacy code (Adex model - Marc Oliver test) which are not compatible with float, LE need clean up ... I know ...

**Pull request merged**
