### PR TITLE
Update the entire viz stack, retag and rebuild

### PR DESCRIPTION
**Pull request by adevress**

### CODE REVIEW

**Comment by adevress** [comment]
ping @hernando  @eile   for tracking

**Comment by hernando** [comment]
Looks like you have to bump Brayns SHA. Try this: a163a81607089a2788c4a4560eca68b379a3d310

**Comment by adevress** [comment]
done and rettriger, let's see

**Comment by adevress** [comment]
Ok problem solved.

The issue was related to the fix done here in Brayns https://github.com/BlueBrain/Brayns/pulls

**Comment by adevress** [comment]
retest this please

**Comment by adevress** [comment]
Ok, new issue related to BlueRepairSDK.

The vmmlib API has been broken again and some symbols moved. will require a patch to BlueRepairSDK

**Pull request merged**
