### PR TITLE
Updated to latest Keyv

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by tribal-tec** [comment]
It needs more changes to make usage of ceph, see https://github.com/BlueBrain/bbp-nixpkgs/pull/594. This PR was just closed, so maybe you have more luck :)

**Comment by adevress** [comment]
@tribal-tec  It was closed because I rebased it and merged it on an other branch Daniel :)

If it's not the case I did a mistake  :D

**Comment by tribal-tec** [comment]
That merge here doesn't seem useful to me as long as keyv does not add ceph dependency. Unless I miss something, then ignore me.

If the PR was merged somewhere else, why is not mentioned at least there? And shouldn't it be in master anyways?

**Comment by favreau** [comment]
Thanks for the comments guys. I am also a bit confused about the branch discussion. My only concern is to have the "Ceph" version of KeyV deployed on the Julich cluster. If the branch you are mentioning is the one that is being used to deploy to Julich, I guess it's all good. But I would need this to be confirmed, and as @tribal-tec wrote, this should also appear in master, so we'll create a new PR for that now.

**Pull request merged**
