### PR TITLE
add bbp analysis framework, update simwriter

### PR DESCRIPTION
**Pull request by genric**
FYI @MWolfR

### CODE REVIEW

**Comment by genric** [comment]
@tristan0x can you merge this one please? Lucky @wizmer is on vacation :)

**Comment by tristan0x** [comment]
Can I review and merge now or do you want to make additional changes @genric ?

**Comment by genric** [comment]
Good that you asked :) We've just discovered some issues which are being fixed, so I'll probably move the analysis framework commit soon. I'll let you know, thanks @tristan0x !

**Comment by genric** [comment]
@tristan0x, this one is ready for merge, thanks!

**Pull request merged**
