### PR TITLE
jenkins: new function to clear Nix cache

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by tristan0x** [comment]
From what you told me, remove the  content of `/nix/store` would be sufficient right?

So what about?

```bash
find /nix/ -mindepth 1 -type d -exec rm -rf \{\} \;
find /nix/ -mindepth 1 -type f -exec rm f \{\} \;
```

Should the function also cleanup user directory?
```
rm -rf $HOME/{.nix-channels,.nix-defexpr,.nix-profile,.config/nixpkgs}
```

**Comment by adevress** [comment]
If you do a function like removing the nix store, I would prefer it is something we can run exceptionally on the Jenkins plan itself than hardcoded in the bbp-nixpkgs utility. 

I fear that someone might run that by mistake one day, and rip off a valid store . I would totally do a stupidity of this kind

**Comment by tristan0x** [comment]
@adevress Do you mean we should put this function in a dedicated bash script so that it has to be sourced before being called?

**Comment by adevress** [comment]
@tristan0x  Yep, something like that

**Comment by tristan0x** [comment]
@adevress moved in new bash script.
Please review and merge.

**Comment by adevress** [comment]
Thx Maitre Gandalf

**Pull request merged**
