### PR TITLE
update BlueJitterSDK

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
Is it possible to also have the gnu module updated to this version?

**Comment by adevress** [comment]
If you update the package, you automatically update the module associated to it.

If you want the module on BBPV / viz cluster to be updated, you need to trigger the "redeployment" jenkins plan

**Comment by mgeplf** [comment]
I triggered this:
https://bbpcode.epfl.ch/ci/job/hpc.redeploy-modules.nix/93/
but on bbpv1, I still only get `nix/nse/bluejittersdk/34c9e`, is that expected? Or should I have access to a `eb83639` version at some point?

**Comment by adevress** [comment]
Yes,

Because the version you see in the module is the version specified in the bluejitter recipe

which currently hardcode '34c9e'

stdenv.mkDerivation rec {
  name = "bluejittersdk-${version}";
  version = "34c9e";
  buildInputs = [ stdenv boost cmake hdf5-cpp pkgconfig gsl bbpsdk ];

The version you specify in Nix can be any arbitrary string, if you want it to be automatically computed from the source revision number, you can use the same approach that the one used in bluepyopt.

https://github.com/BlueBrain/bbp-nixpkgs/blob/master/bbp/nse/bluepyopt/default.nix

version = "${builtins.substring 0 6 src.rev}"

Will define your package version number to be the 6 first character of your source revision.

**Comment by mgeplf** [comment]
Ah, that makes sense.  Didn't realize that's how it was setup - it's been so long.

I'll fix that and make another PR.

**Pull request merged**
