### PR TITLE
Libwebsockets

### PR DESCRIPTION
**Pull request by adevress**
Upstream backport of libwebsockets

### CODE REVIEW

**Comment by adevress** [comment]
@tribal-tec ping for tracking

**Comment by tribal-tec** [comment]
libuv seems to be missing somehow:
```
In file included from /tmp/nix-build-rockets-0.1.0-dev201710.drv-0/Rockets-e84a833/rockets/utils.h:23:0,
                 from /tmp/nix-build-rockets-0.1.0-dev201710.drv-0/Rockets-e84a833/rockets/utils.cpp:20:
/nix/store/l38wsws8q0jvc4ccaqk3ghfhb6d7a4d9-libwebsockets-2.3.0/include/libwebsockets.h:173:16: fatal error: uv.h: No such file or directory
 #include <uv.h>
                ^
compilation terminated.
```

**Comment by tribal-tec** [comment]
looks like it should be a build output as well?

**Comment by adevress** [comment]
How did you include it ? through a nix recipe ?

**Comment by tribal-tec** [comment]
yes, see here
https://github.com/BlueBrain/bbp-nixpkgs/commit/821d9a55757ae6b84514bdd71b683fa7e5931d2f#diff-4e6937a67d3be87bab3af441fe7a32c3

don't merge yet btw :)

**Pull request merged**
