### PR TITLE
spykfunc: remove python2 support.

### PR DESCRIPTION
**Pull request by matz-e**
After discussion with @ferdonline. Tested locally.

### CODE REVIEW

**Comment by tristan0x** [comment]
Are you sure the module is not used?

**Comment by matz-e** [comment]
@arsenius7 is our only user right now. I'd be in favor of just removing py2 support and move to py3, as compatibility shims are getting a little out of bounds.

**Comment by tristan0x** [comment]
@arsenius7 Do you need spykfunc for Python 2 or can we get rid of it?

**Comment by tristan0x** [comment]
Thank you for the quick reply @arsenius7 
Let's get rid of Python 2 then !

**Pull request merged**
