### PR TITLE
Revised fetchGitExternal support for subdirectories

### PR DESCRIPTION
**Pull request by arsenius7**

### CODE REVIEW

**Comment by adevress** [comment]
test this please

**Comment by arsenius7** [comment]
you are too fast :)

**Comment by arsenius7** [comment]
Do I get it right that bluerepairsdk is the only package using this option?

**Comment by adevress** [comment]
@arsenius7  You are right

**Comment by adevress** [comment]
add to whitelist

**Comment by adevress** [comment]
ok to test

**Comment by adevress** [comment]
test this please

**Pull request merged**
