### PR TITLE
New mdtest benchmark utility

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by adevress** [comment]
sounds good to me.

Could you add if possible two things:
- One module "nix/bench/mdtest" where you can use it ( you can add them under bbp/modules )
- One "target" module ( like module.all ) but named ( module.benchs ) that where all the bench related modules would be built in.

Once it's done, I can configure Jenkins to build "modules.bench" by default. I would like to avoid to put it in "modules.all" if they are not module that we deployed on non-BBP machines

**Comment by tristan0x** [comment]
@adevress I added what you asked. Well ... I think I did :)
If the patch suits you, I will update both *hpc.all.module.nix* and *hpc.all.module.nix.github* Jenkins projects.

**Comment by adevress** [comment]
syntax error on the last one ;)

**Comment by tristan0x** [comment]
retest this please

**Comment by tristan0x** [comment]
@adevress please merge or gimme the credentials!

**Comment by adevress** [comment]
Tu as les deux maintenant :D

**Comment by tristan0x** [comment]
Thank you

**Pull request merged**
