### PR TITLE
Update Rockets to latest

### PR DESCRIPTION
**Pull request by favreau**

### CODE REVIEW

**Comment by favreau** [comment]
This is required for Brayns 0.5.0 to compile

**Comment by adevress** [comment]
@favreau @rdumusc  You have a compilation issue with jsonrpc guys 

https://bbpcode.epfl.ch/ci/job/hpc.all.module.nix.github/platform=nix/1529/console

**Comment by adevress** [comment]
ping :)

**Comment by adevress** [comment]
The error

**Pull request merged**
