### PR TITLE
Bump reportinglib to latest master

### PR DESCRIPTION
**Pull request by ferdonline**
records_max_buffer_size_hint required by neurdamus master

### CODE REVIEW

**Comment by ferdonline** [comment]
retest this please

**Comment by ferdonline** [comment]
retest this please

**Comment by ferdonline** [comment]
@tristan0x Whats the policy for this kind of updates? As-required (like this change) or release style (a bunch of packages bumped?)

**Comment by tristan0x** [comment]
Bump your code whenever you want @ferdonline !
Once this PR is merged, you can then deploy the latest modules on BB5 by starting a build of  `hpc.redeploy-modules.nix` Jenkins project.

**Pull request merged**
