### PR TITLE
Bump Brion

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by adevress** [comment]
Can you update the shasum Juan ? ;) it's in the build log

**Comment by hernando** [comment]
I thought I had already done it

**Comment by hernando** [comment]
When does the updated Brion module become available in the vizcluster?

**Comment by tristan0x** [comment]
Hello @hernando
You simply have to fire the `hpc.redeploy-modules.nix` Jenkins plan to sync
vizcluster modules.

Tristan Carel

**Comment by hernando** [comment]
Thanks!

**Pull request merged**
