### PR TITLE
Update viz stack to 2017.R1 release

### PR DESCRIPTION
**Pull request by tribal-tec**
Don't merge yet. Needs https://github.com/BlueBrain/Brion/pull/162 and other software. Just started :)

### CODE REVIEW

**Comment by adevress** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by adevress** [comment]
add to whitelist

**Comment by adevress** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by tribal-tec** [comment]
Ok, lgtm now. Feel free to merge.

**Comment by adevress** [comment]
Thank you :) Perfect

**Pull request merged**
