### PR TITLE
cython: 0.27.3 -> 0.29.10

### PR DESCRIPTION
**Pull request by tristan0x**

### CODE REVIEW

**Comment by pramodk** [comment]
@tristan0x : curious about the dependency...is this for flatIndex?

**Comment by tristan0x** [comment]
STEPS simulator. I need `-E` command line option.

**Comment by pramodk** [comment]
STEPS is also in Spack right? Better to switch there as we have officially deprecated nix?

**Comment by tristan0x** [comment]
> STEPS is also in Spack right? Better to switch there as we have officially deprecated nix?

CI is not using spack yet.

**Pull request merged**
